config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  
  resources :articles
  resources :comments
  
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :comments
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1200 }
  validates :user_id, presence: true
  has_one_attached :picture
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end
  
  def show
    @comments = @article.comments.all
    @comment = @article.comments.build
    @userbio = @article.user
     
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description, :picture, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago,
                  last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>  
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <% if logged_in? && (current_user == article.user) %>
          <div class="article-actions">
            <%= link_to "Edit article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
            <%= button_to "Delete this article", article_path(article), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete this article?" }, 
                                                class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>  
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :post_picture %>
  </div>


  <div class="form-group">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </div>
    </div>
  </div>



  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div align="center"><%= render "layouts/titleblock" %>	</div>

<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div align="center"><%= render "layouts/titleblock_art" %>	</div>
<br>
  <% @articles.each do |article| %>
<div class="row gutters">
  <div class="col col-6 sayit_pr_15">
    <h2 class="sayit_mb_20">
      <%= article.title %>
    </h2>
    <strong> Author: </strong>
    <%= article.user.username %>
      <br>
      <p class="sayit_mb_40">
        <%= truncate(article.description, length: 500) %>
      </p>

      <div class="sayit_popup_button_widget">
        <div class="sayit_widget_container sayit_mb_50">
          <div class="sayit_popup_button_wrapper">
            <div class="sayit_popup_button_popup">
              <div class="sayit_popup_button_popup_close"></div>
              <div class="sayit_popup_button_content_cont">
                <%= article.description%>
              </div>
            </div>
            <a class="sayit_popup_button" href="javascript:void(0)">Read More</a>
          </div>
        </div>
      </div>
  </div>

  <div class="col col-6 sayit_pl_15 sayit_md_padding_0 sayit_md_mb_40">
    <% if article.picture.present? %>
      <%= image_tag article.picture, width: '100%'  %>
        <% end %>
  </div>
</div>

<p> 
<div>
  <% if logged_in? %>
    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary" %> 
    <%= link_to 'Show', article_path(article), class: "btn btn-xs btn-primary" %>
    <%= button_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
 </div>     
<hr>
 <% end %>
</p>

app/views/articles/new.html.erb
<div align="center"><%= render 'layouts/titleblock_artnew' %>  </div>
<br>
  <%= render 'form', article: @article %>
  <%= link_to 'Back', articles_path %>

  <% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
  <% @article.errors.full_messages.each do |msg|%>
  <li><%= msg %></li>
  <% end %>
 </ul>
  <% end %>

app/views/articles/show.html.erb
<div align="center"><%= render "layouts/titleblock" %>	</div>

<div>
  <h2 align="center">Title: <%= @article.title %></h2>
</div>


<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by: <%= link_to @article.user.username, user_path(@article.user) %></li> 
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

  
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
<div class="col-md-9">
  <%= image_tag(@article.picture, width: '100%') if @article.picture.present? %>
  
 <p>
  <%= simple_format(@article.description) %>
  </p>
  
 
  <div>
 
<strong>About Author: </strong><%= @article.user.userbio %>
   
  </div>
 
  
              
  <h3>Comments</h3>
  <% @comments.each do |comment| %>
  <div>
    <strong><%= comment.author_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%= button_to 'Delete Comment', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-xs btn-danger" %></p>
  </div>
  <% end %>
  
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
 
  
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <p>
    

  <div class="article-actions" >
   
      <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-xs btn-primary"  %> 
      <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
      <%= button_to "Delete this article", article_path(@article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this article?" }, 
                                          class: "btn btn-xs btn-danger" %>
    

  </div>
  

  
    </p>
</div>
<%= link_to 'Back', articles_path %>
</div>