config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  
  resources :articles
  resources :comments
  
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/views/layouts/_categoriesblock.html.erb
					<!-- Info Boxes -->
					<div class="row">
						<div class="col col-6 push-center">
							<div class="sayit_widget_title">
								<div class="sayit_widget_container sayit_text_align_center sayit_mb_60">
									<h2 class="sayit_element_heading sayit_view_type_1">View Articles by Categories</h2>
									<p class="sayit_subtitle_cont">These are a great collection of various articles from different categories. Click on a category to view related articles</p>
								</div>
							</div>
						</div>
					</div>

					<div class="row gutters">
						<!-- Info Box 1 -->
						<div class="col col-4 sayit_pr_10 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_usa.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380" data-tilt data-tilt-easing="linear" data-tilt-max="20">
                        <%= image_tag('img_1')%>
												<div class="sayit_inbo_box_content sayit_no_description">
													<div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
									           
                              <% if  Category.first.present? %>
                                <%= link_to Category.first.name %>
                              <% end %>
                     </h3>
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>

						<!-- Info Box 2 -->
							<div class="col col-4 sayit_pr_5 sayit_pl_5 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_india.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380" data-tilt data-tilt-easing="linear" data-tilt-max="20">
												<%= image_tag ("img_2") %>
                        <div class="sayit_inbo_box_content sayit_no_description">
                          <div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
                                <% if  Category.second.present? %>
                                <%= link_to Category.second.name %>
                                <% end %>
                              </h3>
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>

						<!-- Info Box 3 -->
						<div class="col col-4 sayit_pl_10 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_germany.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380"  data-tilt data-tilt-easing="linear" data-tilt-max="20">
												<%= image_tag ("img_3") %>
                        <div class="sayit_inbo_box_content sayit_no_description">
													<div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
                              <% if  Category.third.present? %>
                                <%= link_to Category.third.name %>
                             <% end %>
                            </h3>
                             
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>

						<!-- Info Box 4 -->
						<div class="col col-4 sayit_pr_10 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_turkey.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380"  data-tilt data-tilt-easing="linear" data-tilt-max="20">
												<%= image_tag ("img_1") %>
                        <div class="sayit_inbo_box_content sayit_no_description">
													<div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
                              
                                <% if  Category.fourth.present? %>
                                <%= link_to Category.fourth.name %>
                                <% end %>
                            </h3>
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>

						<!-- Info Box 5 -->
						<div class="col col-4 sayit_pl_5 sayit_pr_5 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_uk.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380" data-tilt data-tilt-easing="linear" data-tilt-max="20">
												<%= image_tag ("img_2") %>
                        <div class="sayit_inbo_box_content sayit_no_description">
													<div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
                              
                                <% if  Category.fifth.present? %>
                                <%= link_to Category.fifth.name %>
                                <% end %>
                            </h3>
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>

						<!-- Info Box 6 -->
						<div class="col col-4 sayit_pl_10 sayit_mb_40 sayit_md_padding_0 sayit_md_mb_40">
							<div class="sayit_info_box_widget">
								<div class="sayit_widget_container">
									<div class="sayit_info_box_item view_type_3">
										<a href="places_france.html">
											<div class="sayit_info_box_item_inner sayit_js_bg_image sayit_parallax_mode sayit_mobile_height_380" data-tilt data-tilt-easing="linear" data-tilt-max="20">
												<%= image_tag ("img_3") %>
                        <div class="sayit_inbo_box_content sayit_no_description">
													<div class="sayit_info_box_title sayit_text_align_center">
														<h3 class="sayit_js_color" data-color="#ffffff">
                                <% #if  Category.find(6).present? %>
                                <%#= link_to Category.find(6).name %>
                                <%# end %>
                            </h3>
													</div>
												</div>
											</div>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_footer.html.erb
	<!-- Footer -->

<div class="sayit_footer">
		<!-- Footer Instagram -->
		<div class="sayit_photostream">
			<div class="instagallery">
				<!-- Item 1 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
						<%= image_tag ("Blog_1") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								2
							</span>

							<span>
								<i class="fa fa-comment"></i>
								0
							</span>
						</span>
					</a>
				</div>

				<!-- Item 2 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
						<%= image_tag ("Blog_2") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								2
							</span>

							<span>
								<i class="fa fa-comment"></i>
								1
							</span>
						</span>
					</a>
				</div>

				<!-- Item 3 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
						<%= image_tag ("Blog_3") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								2
							</span>

							<span>
								<i class="fa fa-comment"></i>
								1
							</span>
						</span>
					</a>
				</div>

				<!-- Item 4 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
						<%= image_tag ("Blog_4") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								2
							</span>

							<span>
								<i class="fa fa-comment"></i>
								1
							</span>
						</span>
					</a>
				</div>

				<!-- Item 5 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
						<%= image_tag ("Blog_5") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								1
							</span>

							<span>
								<i class="fa fa-comment"></i>
								0
							</span>
						</span>
					</a>
				</div>

				<!-- Item 6 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
							<%= image_tag ("Blog_6") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								1
							</span>

							<span>
								<i class="fa fa-comment"></i>
								1
							</span>
						</span>
					</a>
				</div>

				<!-- Item 7 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
							<%= image_tag ("Blog_7") %>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								1
							</span>

							<span>
								<i class="fa fa-comment"></i>
								1
							</span>
						</span>
					</a>
				</div>

				<!-- Item 8 -->
				<div class="ig-item">
					<a href="javascript:void(0)">
							<%= image_tag ("Blog_8")%>

						<span class="ig-likes-comments">
							<span>
								<i class="fa fa-heart"></i>
								1
							</span>

							<span>
								<i class="fa fa-comment"></i>
								0
							</span>
						</span>
					</a>
				</div>
			</div>
		</div>


    
		<!-- Back To Top -->
		<a class="sayit_back_to_top" href="javascript:void(0)">Top</a>

		<footer class="sayit_footer_type_simple">
			<div class="row">
				<div class="col col-12">
					<div class="row align-middle">
						<div class="col col-2 sayit_footer_logo_container">
							<a class="sayit_image_logo sayit_retina" href="<% root_path %>"></a>
						</div>

						<div class="col col-10 sayit_footer_menu_container">
							<div class="menu-footer-menu-container">
								<ul class="sayit_footer_menu">
                  <!--<li class="menu-item"><%= link_to "Home", root_path %></li> -->
                  <!--<li class="menu-item"><%= link_to "About", about_path %></li> -->
                 <li class="menu-item" text-center><small>Copyright &copy; Elisha Tigah</a> </small></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</div>

app/views/layouts/_messages.html.erb
<br>
<br>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_slider.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="800">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img3"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">
                          <div class="sayit_post_category_cont">
														<%= link_to "Sign up now", signup_path%>
													</div>

													<h2 class="sayit_post_title" style="color:white;">The E Blog App</h2>

													<div class="sayit_post_slider_nav_buttons_cont">
														<a class="sayit_prev_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_0" data-number="0"><i class="fa fa-angle-left"></i></a>
														<a class="sayit_next_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_2" data-number="2"><i class="fa fa-angle-right"></i></a>
													</div>
												</div>
											</div>
										</div>

										<!-- Item 2 -->
										<div class="sayit_post_slider_item item_2" data-number="2">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img2"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">
                          
													<div class="sayit_post_category_cont">
														<%= link_to "Sign up now", signup_path%>
													</div>

													<h2 class="sayit_post_title"><a href="post_image.html">The Best Blog App Ever</a></h2>

													<div class="sayit_post_slider_nav_buttons_cont">
														<a class="sayit_prev_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_1" data-number="1"><i class="fa fa-angle-left"></i></a>
														<a class="sayit_next_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_3" data-number="3"><i class="fa fa-angle-right"></i></a>
													</div>
												</div>
											</div>
										</div>

										<!-- Item 3 -->
										<div class="sayit_post_slider_item item_3" data-number="3">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">
                          
                          <div class="sayit_post_category_cont">
														<%= link_to "Sign up now", signup_path%>
													</div>

													<h2 class="sayit_post_title"><a href="post_video.html">Blog away...</a></h2>

													<div class="sayit_post_slider_nav_buttons_cont">
														<a class="sayit_prev_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_2" data-number="2"><i class="fa fa-angle-left"></i></a>
														<a class="sayit_next_post_slide_button sayit_inner_post_slide_button" href="javascript:void(0)" data-slide=".item_4" data-number="4"><i class="fa fa-angle-right"></i></a>
													</div>
												</div>
											</div>
										</div>

										<!-- Slider Navigation -->
										<div class="sayit_post_slider_nav">
											<a class="sayit_post_slider_nav_button button_1" href="javascript:void(0)" data-slide=".item_1"></a>
											<a class="sayit_post_slider_nav_button button_2" href="javascript:void(0)" data-slide=".item_2"></a>
											<a class="sayit_post_slider_nav_button button_3" href="javascript:void(0)" data-slide=".item_3"></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

                          <h2 class="sayit_post_title" style="color:white;"></h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_art.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

                          <h2 class="sayit_post_title" style="color:white;"></a>Listing all Articles</a></h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_artnew.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="color:white;">Create a New Article</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_cat.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">Category: <%= @category.name %></h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_login.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;" >Log In</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_newcat.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">Create a New Category</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_profile.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">Edit Your Account</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_signup.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">Sign Up for E Blogging</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_user.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">All E Bloggers</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

app/views/layouts/_titleblock_userwelcome.html.erb
					<!-- Post Slider -->
					<div class="sayit_fullwidth_block">
						<div class="sayit_post_slider_widget">
							<div class="sayit_widget_container">
								<div class="sayit_post_slider_cont">
									<div class="sayit_post_slider_wrapper" id="sayit_post_slider_123344" data-autoplay="off" data-pause="yes" data-speed="8000" data-default-height="500">
										<!-- Item 1 -->
										<div class="sayit_post_slider_item item_1" data-number="1">
											<div class="sayit_slider_item_wrapper sayit_js_bg_image" > <%= image_tag ( "img1"), class: "sayit_slider_item_wrapper sayit_js_bg_image" %>
												<div class="sayit_overlay"></div>

												<div class="sayit_post_meta_cont">

													<h2 class="sayit_post_title" style="text-align:center; color:white;">Welcome to <%= @user.username %>'s page</h2>
          
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>